### ISSUE TITLE
NPE on Config.save

### ISSUE THREAD

**Issue by Fargus5** [Rsl1122/Plan-PlayerAnalytics#487] opened 2017-12-29 21:16 UTC
```
java.lang.NullPointerException
   java.nio.file.Files.provider(Files.java:97)
   java.nio.file.Files.newOutputStream(Files.java:216)
   java.nio.file.Files.write(Files.java:3351)
   com.djrapitops.plugin.api.config.Config.save(Config.java:164)
   com.djrapitops.plugin.api.config.ConfigNode.save(ConfigNode.java:208)
   main.java.com.djrapitops.plan.data.plugin.PluginsConfigSection.createSection(PluginsConfigSection.java:36)
   main.java.com.djrapitops.plan.data.plugin.HookHandler.addPluginDataSource(HookHandler.java:56)
   com.djrapitops.pluginbridge.plan.Hook.addPluginDataSource(Hook.java:58)
   com.djrapitops.pluginbridge.plan.advancedachievements.AdvancedAchievementsHook.hook(AdvancedAchievementsHook.java:39)
   com.djrapitops.pluginbridge.plan.Bridge.hook(Bridge.java:75)
   main.java.com.djrapitops.plan.data.plugin.HookHandler.<init>(HookHandler.java:32)
   main.java.com.djrapitops.plan.Plan.onEnable(Plan.java:206)
   org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
   org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
   org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
   org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
   org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
   net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
   net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
   net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
   net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
   net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
   java.lang.Thread.run(Thread.java:745)
Error was logged: Dec 29, 22:13:08
java.lang.NullPointerException
   java.nio.file.Files.provider(Files.java:97)
   java.nio.file.Files.newOutputStream(Files.java:216)
   java.nio.file.Files.write(Files.java:3351)
   com.djrapitops.plugin.api.config.Config.save(Config.java:164)
   com.djrapitops.plugin.api.config.ConfigNode.save(ConfigNode.java:208)
   main.java.com.djrapitops.plan.data.plugin.PluginsConfigSection.createSection(PluginsConfigSection.java:36)
   main.java.com.djrapitops.plan.data.plugin.HookHandler.addPluginDataSource(HookHandler.java:56)
   com.djrapitops.pluginbridge.plan.Hook.addPluginDataSource(Hook.java:58)
   com.djrapitops.pluginbridge.plan.essentials.EssentialsHook.hook(EssentialsHook.java:34)
   com.djrapitops.pluginbridge.plan.Bridge.hook(Bridge.java:75)
   main.java.com.djrapitops.plan.data.plugin.HookHandler.<init>(HookHandler.java:32)
   main.java.com.djrapitops.plan.Plan.onEnable(Plan.java:206)
   org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
   org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
   org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
   org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
   org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
   net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
   net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
   net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
   net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
   net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
   java.lang.Thread.run(Thread.java:745)
Error was logged: Dec 29, 22:13:08
java.lang.NullPointerException
   java.nio.file.Files.provider(Files.java:97)
   java.nio.file.Files.newOutputStream(Files.java:216)
   java.nio.file.Files.write(Files.java:3351)
   com.djrapitops.plugin.api.config.Config.save(Config.java:164)
   com.djrapitops.plugin.api.config.ConfigNode.save(ConfigNode.java:208)
   main.java.com.djrapitops.plan.data.plugin.PluginsConfigSection.createSection(PluginsConfigSection.java:36)
   main.java.com.djrapitops.plan.data.plugin.HookHandler.addPluginDataSource(HookHandler.java:56)
   com.djrapitops.pluginbridge.plan.Hook.addPluginDataSource(Hook.java:58)
   com.djrapitops.pluginbridge.plan.kingdoms.KingdomsHook.hook(KingdomsHook.java:25)
   com.djrapitops.pluginbridge.plan.Bridge.hook(Bridge.java:75)
   main.java.com.djrapitops.plan.data.plugin.HookHandler.<init>(HookHandler.java:32)
   main.java.com.djrapitops.plan.Plan.onEnable(Plan.java:206)
   org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
   org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
   org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
   org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
   org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
   net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
   net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
   net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
   net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
   net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
   java.lang.Thread.run(Thread.java:745)
Error was logged: Dec 29, 22:13:08
java.lang.NullPointerException
   java.nio.file.Files.provider(Files.java:97)
   java.nio.file.Files.newOutputStream(Files.java:216)
   java.nio.file.Files.write(Files.java:3351)
   com.djrapitops.plugin.api.config.Config.save(Config.java:164)
   com.djrapitops.plugin.api.config.ConfigNode.save(ConfigNode.java:208)
   main.java.com.djrapitops.plan.data.plugin.PluginsConfigSection.createSection(PluginsConfigSection.java:36)
   main.java.com.djrapitops.plan.data.plugin.HookHandler.addPluginDataSource(HookHandler.java:56)
   com.djrapitops.pluginbridge.plan.Hook.addPluginDataSource(Hook.java:58)
   com.djrapitops.pluginbridge.plan.litebans.LiteBansHook.hook(LiteBansHook.java:40)
   com.djrapitops.pluginbridge.plan.Bridge.hook(Bridge.java:75)
   main.java.com.djrapitops.plan.data.plugin.HookHandler.<init>(HookHandler.java:32)
   main.java.com.djrapitops.plan.Plan.onEnable(Plan.java:206)
   org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
   org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
   org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
   org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
   org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
   net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
   net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
   net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
   net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
   net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
   java.lang.Thread.run(Thread.java:745)
Error was logged: Dec 29, 22:13:08
java.lang.NullPointerException
   java.nio.file.Files.provider(Files.java:97)
   java.nio.file.Files.newOutputStream(Files.java:216)
   java.nio.file.Files.write(Files.java:3351)
   com.djrapitops.plugin.api.config.Config.save(Config.java:164)
   com.djrapitops.plugin.api.config.ConfigNode.save(ConfigNode.java:208)
   main.java.com.djrapitops.plan.data.plugin.PluginsConfigSection.createSection(PluginsConfigSection.java:36)
   main.java.com.djrapitops.plan.data.plugin.HookHandler.addPluginDataSource(HookHandler.java:56)
   com.djrapitops.pluginbridge.plan.Hook.addPluginDataSource(Hook.java:58)
   com.djrapitops.pluginbridge.plan.vault.VaultHook.hook(VaultHook.java:44)
   com.djrapitops.pluginbridge.plan.Bridge.hook(Bridge.java:75)
   main.java.com.djrapitops.plan.data.plugin.HookHandler.<init>(HookHandler.java:32)
   main.java.com.djrapitops.plan.Plan.onEnable(Plan.java:206)
   org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
   org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
   org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
   org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:377)
   org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:327)
   net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421)
   net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382)
   net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337)
   net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
   net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544)
   java.lang.Thread.run(Thread.java:745)
Error was logged: Dec 29, 22:13:08
```

**Comment by Rsl1122** [comment] 2018-01-14 20:31
Duplicate of #459 (Now reopened)

**Closed** 2018-01-14 20:32 UTC
Labels: Bug, Duplicate
