### ISSUE TITLE
JRE Dump on Shutdown

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#515] opened 2018-01-29 14:30 UTC
Spigot 1.12.2 latest
Plan 4.1.5-DEV1 (the second)

No errors on startup. On shutdown, [JRE dump](https://blackdog.straight8.com/drops/hs_err_pid15300.log). Please note when you have a copy, so I can remove it.

**Comment by Rsl1122** [comment] 2018-01-29 14:41
saved the log

**Comment by SlimeDog** [comment] 2018-01-29 14:46
removed.

Intererstingly, this happened only on one of my two test servers. They are functionally identical, but the backup is a day behind wrt data.

**Comment by Rsl1122** [comment] 2018-01-29 14:55
From what I can tell it was processing a SQLite query in one of the ProcessingQueue Consumer async tasks at the time of crash, but other than that I have no idea.
I don't think I can do anything to fix this to be honest

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 10552  org.sqlite.core.NativeDB.column_long(JI)J (0 bytes) @ 0x00007f572ec816d8 [0x00007f572ec816a0+0x38]
J 13533 C2 com.djrapitops.plan.system.database.databases.sql.tables.TPSTable$1.processResults(Ljava/sql/ResultSet;)Ljava/util/List; (118 bytes) @ 0x00007f572f513ef4 [0x00007f572f513ce0+0x214]
j  com.djrapitops.plan.system.database.databases.sql.tables.TPSTable$1.processResults(Ljava/sql/ResultSet;)Ljava/lang/Object;+2
j  com.djrapitops.plan.system.database.databases.sql.processing.QueryStatement.executeQuery(Ljava/sql/PreparedStatement;)Ljava/lang/Object;+26
j  com.djrapitops.plan.system.database.databases.sql.tables.Table.query(Lcom/djrapitops/plan/system/database/databases/sql/processing/QueryStatement;)Ljava/lang/Object;+18
j  com.djrapitops.plan.system.database.databases.sql.tables.TPSTable.getTPSData(Ljava/util/UUID;)Ljava/util/List;+59
j  com.djrapitops.plan.system.database.databases.sql.operation.SQLFetchOps.getTPSData(Ljava/util/UUID;)Ljava/util/List;+5
j  com.djrapitops.plan.utilities.html.HtmlStructure.createServerContainer()Ljava/lang/String;+135
j  com.djrapitops.plan.system.info.BukkitInfoSystem.updateNetworkPage()V+0
j  com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.generateAndCache(Ljava/util/UUID;)V+36
j  com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.runLocally()V+5
j  com.djrapitops.plan.system.info.BukkitInfoSystem.runLocally(Lcom/djrapitops/plan/system/info/request/InfoRequest;)V+18
j  com.djrapitops.plan.system.info.InfoSystem.generateAnalysisPage(Ljava/util/UUID;)V+21
j  com.djrapitops.plan.command.commands.AnalyzeCommand.lambda$onCommand$0([Ljava/lang/String;Lcom/djrapitops/plugin/command/ISender;)V+45
j  com.djrapitops.plan.command.commands.AnalyzeCommand$$Lambda$346.process()V+12
j  com.djrapitops.plan.system.processing.ProcessConsumer.consume(Lcom/djrapitops/plan/system/processing/Processor;)V+42
j  com.djrapitops.plan.system.processing.ProcessConsumer.consume(Ljava/lang/Object;)V+5
j  com.djrapitops.plan.utilities.queue.Consumer.run()V+17
j  com.djrapitops.plugin.task.RunnableFactory$1.run()V+12
j  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run()V+4
j  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run()V+53
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
```

**Comment by SlimeDog** [comment] 2018-01-29 15:07
I perform **plan analyze** as part of the shutdown protocol. If I take that out, no error.

**Comment by Rsl1122** [comment] 2018-01-29 15:21
```
[17:12:42] [Server thread/INFO]: Rsl1122 issued server command: /plan a
[17:12:42] [Craft Scheduler Thread - 8/INFO]: [Plan] Analysis | Beginning analysis of user data..
[17:12:42] [Craft Scheduler Thread - 8/INFO]: [Plan] [DEBUG] Analysis | Beginning analysis of user data..
[17:12:42] [Craft Scheduler Thread - 8/INFO]: [Plan] Analysis | Fetching Data..
[17:12:42] [Craft Scheduler Thread - 8/INFO]: [Plan] [DEBUG] Analysis | Fetching Data..
[17:12:42] [Server thread/INFO]: Stopping the server
[17:12:42] [Server thread/INFO]: Stopping server
[17:12:42] [Server thread/INFO]: [Plan] Disabling Plan v4.1.5-DEV
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 21: ProcessQueueConsumer, Async.
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 22: ProcessQueueConsumer, Async.
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 23: ProcessQueueConsumer, Async.
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 24: ProcessQueueConsumer, Async.
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 25: ProcessQueueConsumer, Async.
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 26: ProcessQueueConsumer, Async.
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 27: ProcessQueueConsumer, Async.
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 28: ProcessQueueConsumer, Async.
[17:12:42] [Server thread/INFO]: [Plan] Processing unprocessed processors. (0)
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Processing unprocessed processors. (0)
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] | Database (Jan 29, 17:12:15) ------------
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] | Open
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] | Analysis Fetch
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] | Closed
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] | ----------------------------------------
[17:12:42] [Server thread/INFO]: [Plan] Shutting down Webserver..
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Shutting down Webserver..
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 18: DBConnectionPingTask SQLite, Async.
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 19: DBConnectionPingTask SQLite, Async.
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 29: TPSCountTimer, Sync.
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 30: NetworkPageRefreshTask, Async.
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 31: BootAnalysisTask, Async.
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] Ended task 32: PeriodicAnalysisTask, Async.
[17:12:42] [Server thread/INFO]: [Plan] 
[17:12:42] [Server thread/INFO]: [Plan] [DEBUG] 
[17:12:42] [Server thread/INFO]: Saving players
[17:12:42] [Server thread/INFO]: Rsl1122 lost connection: Server closed
--- Crash ---
```

```
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
J 6766  org.sqlite.core.NativeDB.step(J)I (0 bytes) @ 0x00000000053fd4bb [0x00000000053fd480+0x3b]
J 7338 C2 org.sqlite.jdbc3.JDBC3ResultSet.next()Z (132 bytes) @ 0x00000000052a0b7c [0x00000000052a0b00+0x7c]
j  com.djrapitops.plan.system.database.databases.sql.tables.UserInfoTable$6.processResults(Ljava/sql/ResultSet;)Ljava/util/List;+9
j  com.djrapitops.plan.system.database.databases.sql.tables.UserInfoTable$6.processResults(Ljava/sql/ResultSet;)Ljava/lang/Object;+2
j  com.djrapitops.plan.system.database.databases.sql.processing.QueryStatement.executeQuery(Ljava/sql/PreparedStatement;)Ljava/lang/Object;+26
j  com.djrapitops.plan.system.database.databases.sql.tables.Table.query(Lcom/djrapitops/plan/system/database/databases/sql/processing/QueryStatement;)Ljava/lang/Object;+18
j  com.djrapitops.plan.system.database.databases.sql.tables.UserInfoTable.getServerUserInfo(Ljava/util/UUID;)Ljava/util/List;+266
j  com.djrapitops.plan.system.database.databases.sql.operation.SQLFetchOps.getPlayers(Ljava/util/UUID;)Ljava/util/List;+5
j  com.djrapitops.plan.system.database.databases.sql.operation.SQLFetchOps.getServerProfile(Ljava/util/UUID;)Lcom/djrapitops/plan/data/ServerProfile;+12
j  com.djrapitops.plan.utilities.analysis.Analysis.analyze()Lcom/djrapitops/plan/data/calculation/AnalysisData;+74
j  com.djrapitops.plan.utilities.analysis.Analysis.runAnalysis()Lcom/djrapitops/plan/data/calculation/AnalysisData;+29
j  com.djrapitops.plan.utilities.analysis.Analysis.runAnalysisFor(Ljava/util/UUID;Lcom/djrapitops/plan/system/database/databases/Database;Lcom/djrapitops/plan/system/cache/DataCache;)Lcom/djrapitops/plan/data/calculation/AnalysisData;+10
j  com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.analyseAndGetHtml()Ljava/lang/String;+15
j  com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.generateAndCache(Ljava/util/UUID;)V+26
j  com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.runLocally()V+5
j  com.djrapitops.plan.system.info.BukkitInfoSystem.runLocally(Lcom/djrapitops/plan/system/info/request/InfoRequest;)V+18
j  com.djrapitops.plan.system.info.InfoSystem.generateAnalysisPage(Ljava/util/UUID;)V+21
j  com.djrapitops.plan.command.commands.AnalyzeCommand.lambda$onCommand$0([Ljava/lang/String;Lcom/djrapitops/plugin/command/ISender;)V+45
j  com.djrapitops.plan.command.commands.AnalyzeCommand$$Lambda$282.process()V+12
j  com.djrapitops.plan.system.processing.ProcessConsumer.consume(Lcom/djrapitops/plan/system/processing/Processor;)V+42
j  com.djrapitops.plan.system.processing.ProcessConsumer.consume(Ljava/lang/Object;)V+5
j  com.djrapitops.plan.utilities.queue.Consumer.run()V+17
j  com.djrapitops.plugin.task.RunnableFactory$1.run()V+12
j  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run()V+28
j  org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run()V+55
j  com.destroystokyo.paper.ServerSchedulerReportingWrapper.run()V+4
j  java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V+95
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5
j  java.lang.Thread.run()V+11
v  ~StubRoutines::call_stub
```

Possibly caused by not interrupting the Processing Queue consumers when cancelling the tasks.

**Comment by Rsl1122** [comment] 2018-01-30 11:37
Fixed by cancelling tasks onDisable if not reloading the plugin.

Side-effect: Database close causes exceptions if Analysis is being run on disable. These exceptions are non-fatal.

**Closed by Rsl1122** 2018-01-30 11:37 UTC
Labels: Priority: MEDIUM, status: Done, status: Reproduced
