### ISSUE TITLE
500 Internal Error occurred

### ISSUE THREAD

**Issue by Alppuccino** [Rsl1122/Plan-PlayerAnalytics#212] opened 2017-08-01 09:37 UTC
Feel free to use the template below to report your issue, for suggestions you can use whatever works for you :)
Remember to use the Preview button to ensure the errors are displayed properly

If your issue is about a command timeout, please follow the instructions at the bottom of the issue template.

----

**Plan Version:** 3.6.0
**Server Version:** 1.12 (git-Spigot-23b6354-0481ae9)
**Database Type:** MySQL

**Issue Caused by:** /plan analyze after 3.6.0 update

----

**Description:**
When I do /plan analyze it links me to a white page: 
https://gyazo.com/b60cea00e5c75a784ff87c7bb7682f85 looks like that
**Steps to Reproduce:**

1. Update Plan
2. /plan Analyze

**Proposed Solution:**
Something to do with the https update maybe?

----

**Console/Errors.txt/DebugLog.txt contents:**
```
Place any stack traces inside these symbols (```)
```

----

Instructions for reporting timeout issues:

- Enable file debug mode by changing config setting "Debug" to "file"
- Reload the plugin
- Run the command that causes the timeout message to show
- Copy the contents of DebugLog.txt inside the code brackets above

**Comment by Rsl1122** [comment] 2017-08-01 10:35
This error is caused by improperly loading the plugin. A server restart should fix the issue

**Comment by Rsl1122** [comment] 2017-08-01 12:01
Duplicate of #184

**Closed** 2017-08-03 07:19 UTC
Labels: Duplicate, status: Done
