### ISSUE TITLE
After logging in to Plan on BungeeCord side (Plan v4.5.1)

### ISSUE THREAD

**Issue by kalleswe** [Rsl1122/Plan-PlayerAnalytics#838] opened 2018-12-09 16:07 UTC
It told me to report issue here:

This is what I got:
It seems like the SQL query is wrong there and data is missing within the "()".

```
com.djrapitops.plan.api.exceptions.ParseException: com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: SELECT server_id, date, players_online FROM plan_tps WHERE date>1543161906280 AND (); You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1 | Failed to parse network page
    com.djrapitops.plan.utilities.html.pages.NetworkPage.toHtml(NetworkPage.java:88)
    com.djrapitops.plan.system.webserver.response.pages.NetworkPageResponse.(NetworkPageResponse.java:31)
    com.djrapitops.plan.system.webserver.response.ResponseFactory.networkPageResponse(ResponseFactory.java:100)
    com.djrapitops.plan.system.webserver.cache.ResponseCache.lambda$loadResponse$0(ResponseCache.java:63)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2039)
    java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020)
    com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
    com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
    com.djrapitops.plan.system.webserver.cache.ResponseCache.loadResponse(ResponseCache.java:63)
    com.djrapitops.plan.system.webserver.pages.ServerPageHandler.getResponse(ServerPageHandler.java:85)
    com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:159)
    com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:104)
    com.djrapitops.plan.system.webserver.RequestHandler.handle(RequestHandler.java:94)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:645)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
Caused by: com.djrapitops.plan.api.exceptions.database.DBOpException: SQL Failed: SELECT server_id, date, players_online FROM plan_tps WHERE date>1543161906280 AND (); You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
    com.djrapitops.plan.api.exceptions.database.DBOpException.forCause(DBOpException.java:37)
    com.djrapitops.plan.system.database.databases.sql.SQLDB.query(SQLDB.java:372)
    com.djrapitops.plan.system.database.databases.sql.tables.Table.query(Table.java:177)
    com.djrapitops.plan.system.database.databases.sql.tables.TPSTable.getPlayersOnlineForServers(TPSTable.java:350)
    com.djrapitops.plan.system.database.databases.sql.operation.SQLFetchOps.getPlayersOnlineForServers(SQLFetchOps.java:492)
    com.djrapitops.plan.data.store.containers.NetworkContainer.lambda$addServerBoxes$1(NetworkContainer.java:101)
    com.djrapitops.plan.data.store.containers.DataContainer.getValue(DataContainer.java:109)
    com.djrapitops.plan.data.store.containers.NetworkContainer.lambda$addServerBoxes$5(NetworkContainer.java:109)
    com.djrapitops.plan.utilities.formatting.PlaceholderReplacer.addPlaceholderFrom(PlaceholderReplacer.java:37)
    com.djrapitops.plan.utilities.formatting.PlaceholderReplacer.addAllPlaceholdersFrom(PlaceholderReplacer.java:42)
    com.djrapitops.plan.utilities.html.pages.NetworkPage.toHtml(NetworkPage.java:64)
    com.djrapitops.plan.system.webserver.response.pages.NetworkPageResponse.(NetworkPageResponse.java:31)
    com.djrapitops.plan.system.webserver.response.ResponseFactory.networkPageResponse(ResponseFactory.java:100)
    com.djrapitops.plan.system.webserver.cache.ResponseCache.lambda$loadResponse$0(ResponseCache.java:63)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2039)
    java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020)
    com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
    com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
    com.djrapitops.plan.system.webserver.cache.ResponseCache.loadResponse(ResponseCache.java:63)
    com.djrapitops.plan.system.webserver.pages.ServerPageHandler.getResponse(ServerPageHandler.java:85)
    com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:159)
    com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:104)
    com.djrapitops.plan.system.webserver.RequestHandler.handle(RequestHandler.java:94)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:645)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 1
    sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
    com.mysql.jdbc.Util.getInstance(Util.java:408)
    com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
    com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
    com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
    com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
    com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
    com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
    com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
    com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011)
    plan.com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
    plan.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
    com.djrapitops.plan.system.database.databases.sql.processing.QueryStatement.executeQuery(QueryStatement.java:46)
    com.djrapitops.plan.system.database.databases.sql.SQLDB.query(SQLDB.java:369)
    com.djrapitops.plan.system.database.databases.sql.tables.Table.query(Table.java:177)
    com.djrapitops.plan.system.database.databases.sql.tables.TPSTable.getPlayersOnlineForServers(TPSTable.java:350)
    com.djrapitops.plan.system.database.databases.sql.operation.SQLFetchOps.getPlayersOnlineForServers(SQLFetchOps.java:492)
    com.djrapitops.plan.data.store.containers.NetworkContainer.lambda$addServerBoxes$1(NetworkContainer.java:101)
    com.djrapitops.plan.data.store.containers.DataContainer.getValue(DataContainer.java:109)
    com.djrapitops.plan.data.store.containers.NetworkContainer.lambda$addServerBoxes$5(NetworkContainer.java:109)
    com.djrapitops.plan.utilities.formatting.PlaceholderReplacer.addPlaceholderFrom(PlaceholderReplacer.java:37)
    com.djrapitops.plan.utilities.formatting.PlaceholderReplacer.addAllPlaceholdersFrom(PlaceholderReplacer.java:42)
    com.djrapitops.plan.utilities.html.pages.NetworkPage.toHtml(NetworkPage.java:64)
    com.djrapitops.plan.system.webserver.response.pages.NetworkPageResponse.(NetworkPageResponse.java:31)
    com.djrapitops.plan.system.webserver.response.ResponseFactory.networkPageResponse(ResponseFactory.java:100)
    com.djrapitops.plan.system.webserver.cache.ResponseCache.lambda$loadResponse$0(ResponseCache.java:63)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2039)
    java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2037)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2020)
    com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:112)
    com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
    com.djrapitops.plan.system.webserver.cache.ResponseCache.loadResponse(ResponseCache.java:63)
    com.djrapitops.plan.system.webserver.pages.ServerPageHandler.getResponse(ServerPageHandler.java:85)
    com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:159)
    com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:104)
    com.djrapitops.plan.system.webserver.RequestHandler.handle(RequestHandler.java:94)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:645)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
```

**Comment by Rsl1122** [comment] 2018-12-09 16:45
Duplicate of #812

Fixed in 4.5.2

**Closed by Rsl1122** 2018-12-09 16:45 UTC
