### ISSUE TITLE
Random Errors

### ISSUE THREAD

**Issue by RainOfPain125** [Rsl1122/Plan-PlayerAnalytics#530] opened 2018-02-19 20:57 UTC
Instructions for issue reporting:
- Write description of the issue
- Copy possible errors here, If you're using 4.0.7+ head to `<address>/debug` & copy the information to the ticket.

For suggestions use any format you want. :)

----

**Description of the issue**
Errors in console
<REPLACE with error / debug-page contents>
https://pastebin.com/Egsd6Xqr

**Comment by Rsl1122** [comment] 2018-02-24 11:07
I checked the paste earlier and concluded there was only one bug that was not caused by bad configuration of MySQL (`Unknown database 'plan'`)

```
java.lang.NoSuchMethodError: io.minimum.minecraft.superbvote.storage.VoteStorage.getVotes(Ljava/util/UUID;)I
   com.djrapitops.pluginbridge.plan.superbvote.SuperbVoteData.getServerData(SuperbVoteData.java:47)
   com.djrapitops.plan.utilities.analysis.Analysis.lambda$analyzeAdditionalPluginData$4(Analysis.java:128)
   java.util.stream.ForEachOps$ForEachOp$OfRef.accept(Unknown Source)
   java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
   java.util.stream.AbstractPipeline.copyInto(Unknown Source)
   java.util.stream.ForEachOps$ForEachTask.compute(Unknown Source)
   java.util.concurrent.CountedCompleter.exec(Unknown Source)
   java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
   java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
   java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
   java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```
- [x] Fixed
```
java.lang.NoSuchMethodError: io.minimum.minecraft.superbvote.storage.VoteStorage.getVotes(Ljava/util/UUID;)I
   com.djrapitops.pluginbridge.plan.superbvote.SuperbVoteData.getPlayerData(SuperbVoteData.java:35)
   com.djrapitops.plan.data.plugin.HookHandler.getInspectContainersFor(HookHandler.java:96)
   com.djrapitops.plan.system.webserver.response.pages.parts.InspectPagePluginsContent.generateForThisServer(InspectPagePluginsContent.java:42)
   com.djrapitops.plan.system.info.request.GenerateInspectPluginsTabRequest.generateAndCache(GenerateInspectPluginsTabRequest.java:61)
   com.djrapitops.plan.system.info.request.GenerateInspectPluginsTabRequest.runLocally(GenerateInspectPluginsTabRequest.java:67)
   com.djrapitops.plan.system.info.BukkitInfoSystem.runLocally(BukkitInfoSystem.java:32)
   com.djrapitops.plan.system.info.connection.ConnectionSystem.sendInfoRequest(ConnectionSystem.java:80)
   com.djrapitops.plan.system.info.connection.BukkitConnectionSystem.lambda$sendWideInfoRequest$2(BukkitConnectionSystem.java:91)
   com.djrapitops.plan.system.info.connection.WebExceptionLogger.logIfOccurs(WebExceptionLogger.java:24)
   com.djrapitops.plan.system.info.connection.BukkitConnectionSystem.sendWideInfoRequest(BukkitConnectionSystem.java:89)
   com.djrapitops.plan.system.info.request.GenerateInspectPageRequest.generateAndCache(GenerateInspectPageRequest.java:66)
   com.djrapitops.plan.system.info.request.GenerateInspectPageRequest.runLocally(GenerateInspectPageRequest.java:75)
   com.djrapitops.plan.system.info.BukkitInfoSystem.runLocally(BukkitInfoSystem.java:32)
   com.djrapitops.plan.system.info.InfoSystem.sendRequest(InfoSystem.java:97)
   com.djrapitops.plan.system.info.InfoSystem.generateAndCachePlayerPage(InfoSystem.java:63)
   com.djrapitops.plan.system.cache.SessionCache.lambda$null$1(SessionCache.java:58)
   com.djrapitops.plan.system.info.connection.WebExceptionLogger.logIfOccurs(WebExceptionLogger.java:24)
   com.djrapitops.plan.system.cache.SessionCache.lambda$cacheSession$2(SessionCache.java:57)
   com.djrapitops.plan.system.processing.ProcessConsumer.consume(ProcessingQueue.java:80)
   com.djrapitops.plan.system.processing.ProcessConsumer.consume(ProcessingQueue.java:66)
   com.djrapitops.plan.utilities.queue.Consumer.run(Consumer.java:34)
   com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:39)
   org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:58)
   org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
   com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
   java.lang.Thread.run(Unknown Source)
```
- [x] Fixed

These have been fixed in commit ec6fb4106e217f22b40c52f09858363e52fb9d05

**Closed** 2018-02-24 11:07 UTC
Labels: Bug, Complexity: LOW, Multi-Issue, PluginData, status: Done
