### ISSUE TITLE
[3.X.X] player list playtime is problematic

### ISSUE THREAD

**Issue by biffamc** [Rsl1122/Plan-PlayerAnalytics#301] opened 2017-09-28 09:39 UTC
Hello, 
I think there is a problem in the way playtime is displayed in the playerlist.
I know that:
- Whether or not a player is active is determined with 3 values: Last Login, Playtime and Login Times. If the player has logged in in the last 2 weeks, has playtime higher than in the config (mine is default), and has logged in 3 times, the player is considered active.- 
However when i look at the player list I see active players, that I know were online for several hours, with a displayed playtime <10min.
If I enter in the player detalis I can calculate the real time the player was online by multiplying the total login times by the average length of the sessions.
One example is:
in playerlist user is active, playtime 5m28s, login times 13, last seen yesterday
in inspect player user has 13 logins with 16m35s average (around 210 mins)
Is there anything I am missing or is there something wrong?
Thanks for the time you put in this useful project.
Ciao :)

**Comment by Rsl1122** [comment] 2017-09-28 09:44
What version are you using?

If you're using something else other than a 4.0.0 DEV release then this is a duplicate of #278 
Please read the answers there.

4.0.0 is coming out this weekend and fixes this issue (And resets all playtimes due to large database changes and inaccuracies in the old system)

**Comment by biffamc** [comment] 2017-09-28 09:54
yes it is exactly the same issue, sorry I didn't use the search button. i am running 3.X.X i guess.

thanks again

**Comment by Rsl1122** [comment] 2017-09-28 10:04
Ah no problem, I closed that issue recently even though it is present in the currently available version.

**Closed** 2017-10-01 18:47 UTC
Labels: Duplicate, Enhancement, status: Already Fixed
