### ISSUE TITLE
IPAE on server shutdown

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#490] opened 2018-01-07 02:15 UTC
Spigot 1.12.2 latest
Plan 4.1.4
SQLite database

On shutdown:
```
[18:06:56 WARN]: org.bukkit.plugin.IllegalPluginAccessException: Plugin attempted to register task while disabled
[18:06:56 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.validate(CraftScheduler.java:403)
[18:06:56 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.runTaskTimerAsynchronously(CraftScheduler.java:144)
[18:06:56 WARN]:        at org.bukkit.scheduler.BukkitRunnable.runTaskTimerAsynchronously(BukkitRunnable.java:133)
[18:06:56 WARN]:        at com.djrapitops.plugin.task.bukkit.AbsBukkitRunnable.runTaskTimerAsynchronously(AbsBukkitRunnable.java:79)
[18:06:56 WARN]:        at main.java.com.djrapitops.plan.database.databases.SQLiteDB.startConnectionPingTask(SQLiteDB.java:106)
[18:06:56 WARN]:        at main.java.com.djrapitops.plan.database.databases.SQLiteDB.setupDataSource(SQLiteDB.java:47)
[18:06:56 WARN]:        at main.java.com.djrapitops.plan.database.databases.SQLDB.init(SQLDB.java:72)
[18:06:56 WARN]:        at main.java.com.djrapitops.plan.ShutdownHook.run(ShutdownHook.java:56)
```

**Comment by Rsl1122** [comment] 2018-01-14 20:28
Duplicate of #482

**Closed** 2018-01-14 20:29 UTC
Labels: Duplicate, status: Done
