### ISSUE TITLE
NPE

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#41] opened 2017-03-09 04:13 UTC
Spigot 1.11.2
Plan 2.8.0

This occurs occasionally, on quiescent server.

> [20:05:57 WARN]: [Plan] Plugin Plan v2.8.0 generated an exception while executing task 17739
java.lang.NullPointerException
        at main.java.com.djrapitops.plan.utilities.AnalysisUtils.lambda$getNewPlayers$0(AnalysisUtils.java:78) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174) ~[?:1.8.0_121]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_121]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_121]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_121]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_121]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_121]
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:474) ~[?:1.8.0_121]
        at main.java.com.djrapitops.plan.utilities.AnalysisUtils.getNewPlayers(AnalysisUtils.java:79) ~[?:?]
        at main.java.com.djrapitops.plan.utilities.Analysis$1.createPlayerActivityGraphs(Analysis.java:229) ~[?:?]
        at main.java.com.djrapitops.plan.utilities.Analysis$1.run(Analysis.java:145) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar-2017-03-08-0723:git-Spigot-283de8b-4316a8c]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.11.2.jar-2017-03-08-0723:git-Spigot-283de8b-4316a8c]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
[20:07:57 INFO]: [Plan] Cleared 3cf9b867-2577-49d1-affb-7ba8196a0d39 from Cache.

**Comment by SlimeDog** [comment] 2017-03-09 04:42
I think this should be logged as an ERROR rather than a WARN.

**Comment by Rsl1122** [comment] 2017-03-09 08:41
Duplicate of #26 
I did not get answer from the other person having this issue,
Does it throw the error with this version?
https://www.dropbox.com/s/ch8xsjq9r5ob886/Plan-2.8.1-DEV.jar?dl=0
Please run /plan analyze  after installing to see if it throws the error

it says WARN instead of ERROR because this exception was not caught by the plugin.

**Comment by SlimeDog** [comment] 2017-03-09 15:19
Loading up Plan 2.8.1-DEV now. The NPE occurs very infrequently, but I'll keep an eye open.

**Comment by Rsl1122** [comment] 2017-03-09 18:15
Ah I've thought it occurs every time analysis is run.
Maybe it has to do with the clearing of the cache then.
I'll try to figure something out.

**Closed** 2017-03-09 18:52 UTC
Labels: Bug, Duplicate, Priority: HIGH

**Comment by Rsl1122** [comment] 2017-03-09 18:58
The new version uploaded to spigot includes additional fix attempts in case this one didn't fix it.

**Comment by SlimeDog** [comment] 2017-03-10 15:45
Spigot 1.11.2, Plan 2.8.1

If anything, NPEs are more frequent.

> [07:41:07 WARN]: [Plan] Task #5209 for Plan v2.8.1 generated an exception
java.lang.NullPointerException
        at main.java.com.djrapitops.plan.data.cache.InspectCacheHandler$2.run(InspectCacheHandler.java:72) ~[?:?]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
        at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:738) [spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot-1.11.2.jar-2017-03-10-0649:git-Spigot-283de8b-eac8591]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
