### ISSUE TITLE
Error after adding new Sponge server to bungee setup

### ISSUE THREAD

**Issue by BenRulez** [Rsl1122/Plan-PlayerAnalytics#944] opened 2019-03-04 22:07 UTC
com.djrapitops.plan.api.exceptions.ParseException: java.lang.IllegalStateException: Duplicate key 2 | Failed to parse network page
    com.djrapitops.plan.utilities.html.pages.NetworkPage.toHtml(NetworkPage.java:88)
    com.djrapitops.plan.system.webserver.response.pages.NetworkPageResponse.(NetworkPageResponse.java:31)
    com.djrapitops.plan.system.webserver.response.ResponseFactory.networkPageResponse(ResponseFactory.java:101)
    com.djrapitops.plan.system.webserver.cache.ResponseCache.lambda$loadResponse$0(ResponseCache.java:62)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2337)
    java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2335)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2318)
    com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:111)
    com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
    com.djrapitops.plan.system.webserver.cache.ResponseCache.loadResponse(ResponseCache.java:62)
    com.djrapitops.plan.system.webserver.pages.ServerPageHandler.getResponse(ServerPageHandler.java:91)
    com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:159)
    com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:104)
    com.djrapitops.plan.system.webserver.RequestHandler.handle(RequestHandler.java:97)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Duplicate key 2
    java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
    java.util.HashMap.merge(HashMap.java:1254)
    java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
    java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
    java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1696)
    java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
    java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
    com.djrapitops.plan.utilities.html.graphs.special.WorldMap.toGeoCodeCounts(WorldMap.java:63)
    com.djrapitops.plan.utilities.html.graphs.special.WorldMap.(WorldMap.java:42)
    com.djrapitops.plan.utilities.html.graphs.special.SpecialGraphFactory.worldMap(SpecialGraphFactory.java:46)
    com.djrapitops.plan.data.store.containers.NetworkContainer.lambda$addPlayerInformation$11(NetworkContainer.java:173)
    com.djrapitops.plan.data.store.containers.SupplierDataContainer.getValue(SupplierDataContainer.java:95)
    com.djrapitops.plan.data.store.containers.DynamicDataContainer.getValue(DynamicDataContainer.java:71)
    com.djrapitops.plan.utilities.formatting.PlaceholderReplacer.addPlaceholderFrom(PlaceholderReplacer.java:35)
    com.djrapitops.plan.utilities.formatting.PlaceholderReplacer.addAllPlaceholdersFrom(PlaceholderReplacer.java:40)
    com.djrapitops.plan.utilities.html.pages.NetworkPage.toHtml(NetworkPage.java:64)
    com.djrapitops.plan.system.webserver.response.pages.NetworkPageResponse.(NetworkPageResponse.java:31)
    com.djrapitops.plan.system.webserver.response.ResponseFactory.networkPageResponse(ResponseFactory.java:101)
    com.djrapitops.plan.system.webserver.cache.ResponseCache.lambda$loadResponse$0(ResponseCache.java:62)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2337)
    java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2335)
    com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2318)
    com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:111)
    com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:54)
    com.djrapitops.plan.system.webserver.cache.ResponseCache.loadResponse(ResponseCache.java:62)
    com.djrapitops.plan.system.webserver.pages.ServerPageHandler.getResponse(ServerPageHandler.java:91)
    com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:159)
    com.djrapitops.plan.system.webserver.ResponseHandler.getResponse(ResponseHandler.java:104)
    com.djrapitops.plan.system.webserver.RequestHandler.handle(RequestHandler.java:97)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
    sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
    com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
    sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    java.lang.Thread.run(Thread.java:748)

**Comment by Rsl1122** [comment] 2019-03-05 05:44
Duplicate of #942

Please see the comments in the issue for a version with the fix (until 4.7.1 arrives)

**Closed by Rsl1122** 2019-03-05 05:44 UTC
