### ISSUE TITLE
The database file is locked

### ISSUE THREAD

**Issue by Fader-GumGum** [Rsl1122/Plan-PlayerAnalytics#238] opened 2017-08-12 08:53 UTC
This server is running

- CraftBukkit version git-Spigot-5340a52-963b19c (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)
- Plan v3.6.2
Getting this error in Errors.txt:

```
----
main.java.com.djrapitops.plan.data.cache.DataCacheHandler Caught org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
  org.sqlite.core.DB.newSQLException(DB.java:909)
  org.sqlite.core.DB.newSQLException(DB.java:921)
  org.sqlite.core.DB.throwex(DB.java:886)
  org.sqlite.core.DB.exec(DB.java:155)
  org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
  main.java.com.djrapitops.plan.database.databases.SQLDB.commit(SQLDB.java:631)
  main.java.com.djrapitops.plan.database.databases.SQLDB.saveMultipleUserData(SQLDB.java:518)
  main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveCacheOnDisable(DataCacheHandler.java:285)
  main.java.com.djrapitops.plan.Plan.lambda$onDisable$0(Plan.java:254)
  java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  java.util.concurrent.FutureTask.run(Unknown Source)
  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
  java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  java.lang.Thread.run(Unknown Source)
----
```
Getting this in DebugLog.txt
```
| ---------------- | main.java.com.djrapitops.plan.data.cache.DataCacheHandler Caught org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked) (Aug 12, 10:42:18) ------------
| main.java.com.djrapitops.plan.data.cache.DataCacheHandler Caught org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
|   org.sqlite.core.DB.newSQLException(DB.java:909)
|   org.sqlite.core.DB.newSQLException(DB.java:921)
|   org.sqlite.core.DB.throwex(DB.java:886)
|   org.sqlite.core.DB.exec(DB.java:155)
|   org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
|   main.java.com.djrapitops.plan.database.databases.SQLDB.commit(SQLDB.java:631)
|   main.java.com.djrapitops.plan.database.tables.Table.commit(Table.java:184)
|   main.java.com.djrapitops.plan.database.tables.CommandUseTable.saveCommandUse(CommandUseTable.java:108)
|   main.java.com.djrapitops.plan.database.Database.saveCommandUse(Database.java:259)
|   main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveCacheOnDisable(DataCacheHandler.java:280)
|   main.java.com.djrapitops.plan.Plan.lambda$onDisable$0(Plan.java:254)
|   java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
|   java.util.concurrent.FutureTask.run(Unknown Source)
|   java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
|   java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
|   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
|   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
|   java.lang.Thread.run(Unknown Source)
| ---------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
|                  | main.java.com.djrapitops.plan.database.tables.VersionTable Caught org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked) (Aug 12, 10:42:19) ------------
| main.java.com.djrapitops.plan.database.tables.VersionTable Caught org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
|   org.sqlite.core.DB.newSQLException(DB.java:909)
|   org.sqlite.core.DB.newSQLException(DB.java:921)
|   org.sqlite.core.DB.throwex(DB.java:886)
|   org.sqlite.core.NativeDB.prepare_utf8(Native Method)
|   org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
|   org.sqlite.core.DB.prepare(DB.java:227)
|   org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:60)
|   main.java.com.djrapitops.plan.database.tables.Table.execute(Table.java:81)
|   main.java.com.djrapitops.plan.database.tables.VersionTable.createTable(VersionTable.java:29)
|   main.java.com.djrapitops.plan.database.databases.SQLDB.checkConnection(SQLDB.java:142)
|   main.java.com.djrapitops.plan.database.databases.SQLDB.init(SQLDB.java:104)
|   main.java.com.djrapitops.plan.Plan.initDatabase(Plan.java:318)
|   main.java.com.djrapitops.plan.Plan.onEnable(Plan.java:150)
|   main.java.com.djrapitops.plan.command.commands.ReloadCommand.onCommand(ReloadCommand.java:39)
|   com.djrapitops.plugin.command.TreeCommand.onCommand(TreeCommand.java:140)
|   com.djrapitops.plugin.command.bukkit.BukkitCommand.onCommand(BukkitCommand.java:35)
|   org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
|   org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
|   org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:647)
|   org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:633)
|   net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444)
|   net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407)
|   net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
|   net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
|   java.lang.Thread.run(Unknown Source)
| ---------------- | ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| ---------------- | Database (Aug 12, 10:42:15) ------------
| Aug 12, 10:42:15 | SELECT * FROM plan_commandusages
| Aug 12, 10:42:15 | 10 ms     Get CommandUse
| Aug 12, 10:42:15 | INSERT INTO plan_commandusages (command, times_used) VALUES (?, ?)
| Aug 12, 10:42:15 | UPDATE plan_commandusages SET times_used=? WHERE (command=?)
| Aug 12, 10:42:15 | SELECT * FROM plan_version
| Aug 12, 10:42:18 | SELECT age FROM plan_users LIMIT 1
| Aug 12, 10:42:18 | UPDATE plan_users SET geolocation=?, last_gamemode=?, last_gamemode_swap=?, play_time=?, login_times=?, last_played=?, deaths=?, mob_kills=?, contains_bukkit_data=?, opped=?, banned=?, name=?, registered=?, last_world=?, last_world_swap=? WHERE uuid=?
| Aug 12, 10:42:18 | SELECT uuid FROM plan_users
| Aug 12, 10:42:18 | 0 ms      Get Saved UUIDS
| Aug 12, 10:42:18 | Executing userinfo batch update: 1
| Aug 12, 10:42:18 | 0 ms      Insert new UserInfo multiple
| Aug 12, 10:42:18 | 0 ms      Save UserInfo multiple
| Aug 12, 10:42:18 | SELECT uuid, id FROM plan_users
| Aug 12, 10:42:18 | 0 ms      Get User IDS ALL
| Aug 12, 10:42:18 | SELECT * FROM plan_nicknames
| Aug 12, 10:42:18 | 0 ms      Get Nicknames Multiple
| Aug 12, 10:42:18 | INSERT INTO plan_nicknames (user_id, current_nick, nickname) VALUES (?, ?, ?)
| Aug 12, 10:42:18 | 0 ms      Save Nicknames Multiple
| Aug 12, 10:42:18 | SELECT * FROM plan_ips
| Aug 12, 10:42:18 | 0 ms      Get Ips Multiple
| Aug 12, 10:42:18 | INSERT INTO plan_ips (user_id, ip) VALUES (?, ?)
| Aug 12, 10:42:18 | 0 ms      Save Ips Multiple
| Aug 12, 10:42:18 | SELECT * FROM plan_kills
| Aug 12, 10:42:18 | 0 ms      Get Kills multiple
| Aug 12, 10:42:18 | INSERT INTO plan_kills (killer_id, victim_id, weapon, date) VALUES (?, ?, ?, ?)
| Aug 12, 10:42:18 | 0 ms      Save Kills multiple
| Aug 12, 10:42:18 | SELECT * FROM plan_sessions
| Aug 12, 10:42:18 | 0 ms      Get Sessions multiple
| Aug 12, 10:42:18 | 0 ms      Save Sessions multiple
| Aug 12, 10:42:18 | SELECT user_id FROM plan_gamemodetimes
| Aug 12, 10:42:18 | Preparing update of GM Times - Batch Size: 1
| Aug 12, 10:42:18 | SELECT user_id FROM plan_gamemodetimes
| Aug 12, 10:42:18 | UPDATE plan_gamemodetimes SET survival=?, creative=?, adventure=?, spectator=?  WHERE (user_id=?)
| Aug 12, 10:42:18 | Executing GM Times batch: 1
| Aug 12, 10:42:18 | 0 ms      Save GMTimes
| Aug 12, 10:42:18 | SELECT * FROM plan_worlds
| Aug 12, 10:42:18 | SELECT user_id, playtime, world_name FROM plan_world_times, plan_worlds WHERE (plan_worlds.world_id=plan_world_times.world_id)
| Aug 12, 10:42:18 | INSERT INTO plan_world_times (user_id, world_id, playtime) VALUES (?, (SELECT plan_worlds.world_id FROM plan_worlds WHERE (world_name=?)), ?)
| Aug 12, 10:42:18 | UPDATE plan_world_times SET playtime=? WHERE ((SELECT plan_worlds.world_id FROM plan_worlds WHERE (world_name=?))=world_id) AND (user_id=?)
| Aug 12, 10:42:19 | 3209 ms   Init sqlite
| ---------------- | ----------------------------------------
| ---------------- | main.java.com.djrapitops.plan.data.cache.DataCacheHandler Caught org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked) (Aug 12, 10:42:22) ------------
| main.java.com.djrapitops.plan.data.cache.DataCacheHandler Caught org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked)
|   org.sqlite.core.DB.newSQLException(DB.java:909)
|   org.sqlite.core.DB.newSQLException(DB.java:921)
|   org.sqlite.core.DB.throwex(DB.java:886)
|   org.sqlite.core.DB.exec(DB.java:155)
|   org.sqlite.jdbc3.JDBC3Connection.commit(JDBC3Connection.java:174)
|   main.java.com.djrapitops.plan.database.databases.SQLDB.commit(SQLDB.java:631)
|   main.java.com.djrapitops.plan.database.databases.SQLDB.saveMultipleUserData(SQLDB.java:518)
|   main.java.com.djrapitops.plan.data.cache.DataCacheHandler.saveCacheOnDisable(DataCacheHandler.java:285)
|   main.java.com.djrapitops.plan.Plan.lambda$onDisable$0(Plan.java:254)
|   java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
|   java.util.concurrent.FutureTask.run(Unknown Source)
|   java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source)
|   java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
|   java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
|   java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
|   java.lang.Thread.run(Unknown Source)
| ---------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
| ---------------- | Database (Aug 12, 10:42:19) ------------
| Aug 12, 10:42:19 | SELECT * FROM plan_commandusages
| Aug 12, 10:42:22 | 2857 ms   Get CommandUse
| Aug 12, 10:42:22 | INSERT INTO plan_commandusages (command, times_used) VALUES (?, ?)
| Aug 12, 10:42:22 | UPDATE plan_commandusages SET times_used=? WHERE (command=?)
| ---------------- | ----------------------------------------
| ---------------- | Database (Aug 12, 10:42:25) ------------
| Aug 12, 10:42:25 | SELECT * FROM plan_version
| Aug 12, 10:42:25 | DB Schema version: 8
| Aug 12, 10:42:25 | SELECT * FROM plan_version
| Aug 12, 10:42:25 | DB Schema version: 8
| Aug 12, 10:42:25 | SELECT * FROM plan_version
| Aug 12, 10:42:25 | DB Schema version: 8
| Aug 12, 10:42:25 | SELECT * FROM plan_version
| Aug 12, 10:42:25 | DB Schema version: 8
| Aug 12, 10:42:25 | SELECT * FROM plan_version
| Aug 12, 10:42:25 | DB Schema version: 8
| Aug 12, 10:42:25 | SELECT age FROM plan_users LIMIT 1
| Aug 12, 10:42:25 | UPDATE plan_users SET geolocation=?, last_gamemode=?, last_gamemode_swap=?, play_time=?, login_times=?, last_played=?, deaths=?, mob_kills=?, contains_bukkit_data=?, opped=?, banned=?, name=?, registered=?, last_world=?, last_world_swap=? WHERE uuid=?
| Aug 12, 10:42:25 | SELECT uuid FROM plan_users
| Aug 12, 10:42:25 | 0 ms      Get Saved UUIDS
| Aug 12, 10:42:25 | Executing userinfo batch update: 1
| Aug 12, 10:42:25 | 0 ms      Insert new UserInfo multiple
| Aug 12, 10:42:25 | 2 ms      Save UserInfo multiple
| Aug 12, 10:42:25 | SELECT uuid, id FROM plan_users
| Aug 12, 10:42:25 | 0 ms      Get User IDS ALL
| Aug 12, 10:42:25 | SELECT * FROM plan_nicknames
| Aug 12, 10:42:25 | 0 ms      Get Nicknames Multiple
| Aug 12, 10:42:25 | INSERT INTO plan_nicknames (user_id, current_nick, nickname) VALUES (?, ?, ?)
| Aug 12, 10:42:25 | 0 ms      Save Nicknames Multiple
| Aug 12, 10:42:25 | SELECT * FROM plan_ips
| Aug 12, 10:42:25 | 0 ms      Get Ips Multiple
| Aug 12, 10:42:25 | INSERT INTO plan_ips (user_id, ip) VALUES (?, ?)
| Aug 12, 10:42:25 | 0 ms      Save Ips Multiple
| Aug 12, 10:42:25 | SELECT * FROM plan_kills
| Aug 12, 10:42:25 | 0 ms      Get Kills multiple
| Aug 12, 10:42:25 | INSERT INTO plan_kills (killer_id, victim_id, weapon, date) VALUES (?, ?, ?, ?)
| Aug 12, 10:42:25 | 0 ms      Save Kills multiple
| Aug 12, 10:42:25 | SELECT * FROM plan_sessions
| Aug 12, 10:42:25 | 0 ms      Get Sessions multiple
| Aug 12, 10:42:25 | Preparing insertion of sessions - Batch Size: 1
| Aug 12, 10:42:25 | INSERT INTO plan_sessions (user_id, session_start, session_end) VALUES (?, ?, ?)
| Aug 12, 10:42:25 | Executing session batch: 1
| Aug 12, 10:42:25 | 0 ms      Save Sessions multiple
| Aug 12, 10:42:25 | SELECT user_id FROM plan_gamemodetimes
| Aug 12, 10:42:25 | Preparing update of GM Times - Batch Size: 1
| Aug 12, 10:42:25 | SELECT user_id FROM plan_gamemodetimes
| Aug 12, 10:42:25 | UPDATE plan_gamemodetimes SET survival=?, creative=?, adventure=?, spectator=?  WHERE (user_id=?)
| Aug 12, 10:42:25 | Executing GM Times batch: 1
| Aug 12, 10:42:25 | 2 ms      Save GMTimes
| Aug 12, 10:42:25 | SELECT * FROM plan_worlds
| Aug 12, 10:42:25 | SELECT user_id, playtime, world_name FROM plan_world_times, plan_worlds WHERE (plan_worlds.world_id=plan_world_times.world_id)
| Aug 12, 10:42:25 | INSERT INTO plan_world_times (user_id, world_id, playtime) VALUES (?, (SELECT plan_worlds.world_id FROM plan_worlds WHERE (world_name=?)), ?)
| Aug 12, 10:42:25 | UPDATE plan_world_times SET playtime=? WHERE ((SELECT plan_worlds.world_id FROM plan_worlds WHERE (world_name=?))=world_id) AND (user_id=?)
| ---------------- | ----------------------------------------


```
Server log after /plan reload
```
[11:19:56] [Server thread/INFO]: [Plan] Shutting down Webserver..
[11:19:56] [Server thread/INFO]: [Plan] Saving cached data..
[11:19:56] [Server thread/INFO]: [Plan] Player Analytics Disabled.
[11:19:56] [Server thread/INFO]: [Plan] You're running the latest version
[11:19:56] [Server thread/INFO]: [Plan] Using Locale: Default (EN)
[11:19:56] [Server thread/INFO]: [Plan] Database init..
[11:19:59] [pool-93-thread-1/ERROR]: [Plan] main.java.com.djrapitops.plan.data.cache.DataCacheHandler Caught org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked). It has been logged to Errors.txt
[11:20:00] [Server thread/ERROR]: [Plan] main.java.com.djrapitops.plan.database.tables.VersionTable Caught org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked). It has been logged to Errors.txt
[11:20:00] [Server thread/ERROR]: [Plan] Failed to create table: plan_version
[11:20:00] [Server thread/ERROR]: [Plan] Database initialization has failed, disabling Plan.
[11:20:00] [Server thread/ERROR]: [Plan] Database initialization has failed, disabling Plan.
[11:20:00] [Server thread/INFO]: [Plan] Disabling Plan v3.6.2
[11:20:00] [Server thread/INFO]: [Plan] Shutting down Webserver..
[11:20:00] [Server thread/INFO]: [Plan] Saving cached data..
[11:20:00] [Server thread/INFO]: [Plan] Player Analytics Disabled.
[11:20:00] [Server thread/WARN]: Unexpected exception while parsing console command "plan reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'plan' in plugin Plan v3.6.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot-1.12.1.jar:git-Spigot-5340a52-963b19c]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.12.1.jar:git-Spigot-5340a52-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot-1.12.1.jar:git-Spigot-5340a52-963b19c]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:633) [spigot-1.12.1.jar:git-Spigot-5340a52-963b19c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot-1.12.1.jar:git-Spigot-5340a52-963b19c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot-1.12.1.jar:git-Spigot-5340a52-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.1.jar:git-Spigot-5340a52-963b19c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.1.jar:git-Spigot-5340a52-963b19c]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.IllegalStateException: Locale has not been initialized.
	at main.java.com.djrapitops.plan.locale.Locale.get(Locale.java:339) ~[?:?]
	at main.java.com.djrapitops.plan.command.commands.ReloadCommand.onCommand(ReloadCommand.java:40) ~[?:?]
	at com.djrapitops.plugin.command.TreeCommand.onCommand(TreeCommand.java:140) ~[?:?]
	at com.djrapitops.plugin.command.bukkit.BukkitCommand.onCommand(BukkitCommand.java:35) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot-1.12.1.jar:git-Spigot-5340a52-963b19c]
	... 8 more
[11:20:03] [pool-93-thread-1/ERROR]: [Plan] main.java.com.djrapitops.plan.data.cache.DataCacheHandler Caught org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked). It has been logged to Errors.txt
[11:20:06] [pool-94-thread-1/ERROR]: [Plan] main.java.com.djrapitops.plan.data.cache.DataCacheHandler Caught org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked). It has been logged to Errors.txt
[11:20:07] [Server thread/INFO]: larver issued server command: /k map
[11:20:09] [pool-93-thread-1/ERROR]: [Plan] main.java.com.djrapitops.plan.data.cache.DataCacheHandler Caught org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked). It has been logged to Errors.txt
[11:20:12] [pool-94-thread-1/ERROR]: [Plan] main.java.com.djrapitops.plan.data.cache.DataCacheHandler Caught org.sqlite.SQLiteException: [SQLITE_BUSY]  The database file is locked (database is locked). It has been logged to Errors.txt
```

**Comment by Rsl1122** [comment] 2017-08-12 09:22
Try removing database.db-journal & restarting the server

This is caused by faulty commit or restart while commit was in process.

**Comment by Fader-GumGum** [comment] 2017-08-12 09:28
Where to find this "database.db-journal"? In the plugins/Plan map there is only a database.db.

**Comment by Rsl1122** [comment] 2017-08-12 09:29
Alright, so it is not there, does it still trow the exception if you start the plugin?

**Comment by Fader-GumGum** [comment] 2017-08-12 09:51
OK, I restarted the server and the problem seems to be fixed. I think that somehow the database.db file was locked. I will monitor this and see if it happens again.

**Comment by Rsl1122** [comment] 2017-08-12 10:06
Yes, restart usually solves this issue.
It is caused by some transaction not being finished in the database (Usually caused by a reload)

**Comment by Rsl1122** [comment] 2017-08-12 10:06
I'll close this & open again if you comment on this issue.

**Closed by Rsl1122** 2017-08-12 10:06 UTC

**Comment by GuilhermeMelo01** [comment] 2022-07-18 22:28
Whenever you change some data from the table in sqlite you have to commit and delete the ****.db-journal file that will be created where the database file will be.

**Comment by AuroraLS3** [comment] 2022-07-19 04:11
> Whenever you change some data from the table in sqlite you have to commit and delete the ****.db-journal file that will be created where the database file will be.

This issue was resolved by switching to use Write Ahead Log 3 years ago
