### ISSUE TITLE
SocketException: Broken pipe (Write failed)

### ISSUE THREAD

**Issue by mibby** [Rsl1122/Plan-PlayerAnalytics#112] opened 2017-06-04 12:05 UTC
Plan 3.4.1
Paper dev 1104 (Spigot 1.11.2)
MySQL Database

The web socket seems to have crashed on reload. Using MySQL for data storage.

Edit: In fact, it seems the web socket likes to stop working very soon after every initialization (startup / plan reload). It slows to a crawl fast and then eventually becomes unreachable. My live map web socket (dynmap) loads fine and fast, so something must be wrong within analytics.

```
[Jun 04 05:03:26] main.java.com.djrapitops.plan.ui.webserver.Response Caught java.net.SocketException: Broken pipe (Write failed)
[Jun 04 05:03:26]   java.net.SocketOutputStream.socketWrite0(Native Method)
[Jun 04 05:03:26]   java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
[Jun 04 05:03:26]   java.net.SocketOutputStream.write(SocketOutputStream.java:143)
[Jun 04 05:03:26]   main.java.com.djrapitops.plan.ui.webserver.Response.sendStaticResource(Response.java:107)
[Jun 04 05:03:26]   main.java.com.djrapitops.plan.ui.webserver.WebSocketServer$1.run(WebSocketServer.java:78)
[Jun 04 05:03:26]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[Jun 04 05:03:26]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Jun 04 05:03:26]   com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[Jun 04 05:03:26]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Jun 04 05:03:26]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Jun 04 05:03:26]   java.lang.Thread.run(Thread.java:748)
[Jun 04 05:03:26] 
[Jun 04 05:03:26] main.java.com.djrapitops.plan.ui.webserver.Response Caught java.net.SocketException: Broken pipe (Write failed)
[Jun 04 05:03:26]   java.net.SocketOutputStream.socketWrite0(Native Method)
[Jun 04 05:03:26]   java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
[Jun 04 05:03:26]   java.net.SocketOutputStream.write(SocketOutputStream.java:143)
[Jun 04 05:03:26]   main.java.com.djrapitops.plan.ui.webserver.Response.sendStaticResource(Response.java:107)
[Jun 04 05:03:26]   main.java.com.djrapitops.plan.ui.webserver.WebSocketServer$1.run(WebSocketServer.java:78)
[Jun 04 05:03:26]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[Jun 04 05:03:26]   org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[Jun 04 05:03:26]   com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[Jun 04 05:03:26]   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[Jun 04 05:03:26]   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[Jun 04 05:03:26]   java.lang.Thread.run(Thread.java:748)
[Jun 04 05:03:26] 

```

**Comment by mibby** [comment] 2017-06-04 12:34
@Rsl1122 I disabled the location gathering in case that was causing the database to explode, since I had over 20,000 log entries within 10 minutes with a handful of players.

```
  Data:
    GatherLocations: false
```

Upon reloading, the database was connectable again, but then a bunch of ArrayIndexOutOfBoundsExceptions occurred when I gave the link to someone else and he connected with chrome.
http://paste.ubuntu.com/24771619/

**Comment by Rsl1122** [comment] 2017-06-04 12:47
That is very weird, never occurred before, I'll investigate and get back to you.

**Comment by Rsl1122** [comment] 2017-06-04 13:27
When you say that it slows down to a crawl, what do you mean?
Can the pages that give a 403 (for example ip:port/) still be accessed?

Found the cause of ArrayIndexOutOfBounds - Likely caused by accessing **ip:port/code/player** - While it is not supposed to be accessed (Player pages are ip:port/code/player/playername), it is not prevented, will be changed to give 403 in a future update.

As for the SocketException it appears that it might be a case of not closing resources properly. (Not surprised, it is quite old code)
Odd that it hasn't caused any issues for so long (In use since February 2nd).

**Temporary fix until the next update:**
If you have another webserver running on the server, you can export the Html files with the Analysis.Export options to another folder (for example, serving folder of the other webserver),
Then change the alternativeIP options to point to that & turn off the webserver.

**Comment by Rsl1122** [comment] 2017-06-04 13:45
Here is a version with a possible fix, please tell me if it fixes the issue :)
https://www.dropbox.com/s/l7eel0ruz6wvjcf/Plan-3.4.1%2BDEV.jar?dl=0

**Comment by mibby** [comment] 2017-06-04 13:51
> When you say that it slows down to a crawl
Permanently stuck loading forever, unreachable 

> Temporary fix until the next update
That's okay, I don't mind keeping the web socket separate from others that I use. How else would I be able to test functionality? :)

> Here is a version with a possible fix
Wonderful, thanks. I'll update right away and let you know if I notice any issues with it.

**Closed** 2017-06-07 07:16 UTC
Labels: Bug, Priority: HIGH
