### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by BlackBeltPanda** [Rsl1122/Plan-PlayerAnalytics#14] opened 2017-02-15 11:04 UTC
This error showed up after restarting my server: http://pastebin.com/raw/Dg8vBd31

Edit: And this one: http://pastebin.com/raw/Fc4ga8LX

**Comment by Rsl1122** [comment] 2017-02-15 12:31
Same issue as #8
I'll have to look further into this.
Most likely caused by #13 because of Halted data saving (Corrupted data)
Combined #13 to this exception.

Please send me your database file. Do /plan manage backup to copy the database.

**Comment by Rsl1122** [comment] 2017-02-15 12:31
http://pastebin.com/raw/csmNfZeh

**Comment by BlackBeltPanda** [comment] 2017-02-15 14:19
[mysql-backup-Feb-15.zip](https://github.com/Rsl1122/Plan-PlayerAnalytics/files/777307/mysql-backup-Feb-15.zip)

**Comment by Rsl1122** [comment] 2017-02-21 20:14
Fixed in 091e3eb1c50dc5e95e5d2dba0a2ab0db2c9698d0

**Closed by Rsl1122** 2017-02-21 20:14 UTC
Labels: bug, duplicate
