### ISSUE TITLE
NPE first time config file is saved

### ISSUE THREAD

**Issue by RainOfPain125** [Rsl1122/Plan-PlayerAnalytics#525] opened 2018-02-14 06:20 UTC
Instructions for issue reporting:
- Write description of the issue
- Copy possible errors here, If you're using 4.0.7+ head to `<address>/debug` & copy the information to the ticket.

For suggestions use any format you want. :)

----

**Description of the issue**
Just an error
<REPLACE with error / debug-page contents>
https://pastebin.com/rYAGL34L

**Comment by SlimeDog** [comment] 2018-02-14 07:12
Not very useful if you don't include your configuration file. No one is going to try to guess what you did.

**Comment by Rsl1122** [comment] 2018-02-14 07:26
Looks like Plan was trying to generate PluginData config sections based on installed plugins - usually goes away after a reload

**Comment by RainOfPain125** [comment] 2018-02-14 21:33
https://pastebin.com/pmDzY5um

My Config

**Comment by Rsl1122** [comment] 2018-02-24 11:09
Stack trace from referenced issue
```
java.lang.NullPointerException
   java.io.File.(File.java:277)
   com.djrapitops.plugin.api.config.Config.save(Config.java:171)
   com.djrapitops.plugin.api.config.ConfigNode.save(ConfigNode.java:208)
   com.djrapitops.plan.data.plugin.PluginsConfigSection.createSection(PluginsConfigSection.java:36)
   com.djrapitops.plan.data.plugin.HookHandler.addPluginDataSource(HookHandler.java:69)
   com.djrapitops.pluginbridge.plan.Hook.addPluginDataSource(Hook.java:58)
   com.djrapitops.pluginbridge.plan.viaversion.ViaVersionHook.hook(ViaVersionHook.java:48)
   com.djrapitops.pluginbridge.plan.Bridge.hookInto(Bridge.java:47)
   com.djrapitops.pluginbridge.plan.Bridge.hook(Bridge.java:41)
   com.djrapitops.plan.data.plugin.HookHandler.enable(HookHandler.java:40)
   com.djrapitops.plan.system.PlanSystem.enable(PlanSystem.java:95)
   com.djrapitops.plan.system.BukkitSystem.enable(BukkitSystem.java:60)
   com.djrapitops.plan.Plan.onEnable(Plan.java:68)
   org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
   org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
   org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
   org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
   org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
   net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408)
   net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372)
   net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
   net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267)
   net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563)
   java.lang.Thread.run(Thread.java:748)
```
- [ ] Fixed

**Comment by Rsl1122** [comment] 2018-03-31 11:39
Reproduced a similar exception with the following test:

```
    @Test
    public void nullAbsolutePath() throws IOException {
        String absolutePath = null; // <-- Causes the NPE later when the file is used for saving
        File nonExistent = new File(absolutePath);

        Config config = new Config(nonExistent);
        config.copyDefaults(copyFromFile);
        config.save();
        ConfigNode node = config.getConfigNode("Test");
        node.set("Example.Test", true);
        node.save(); // <-- Exception

        assertTrue(config.getBoolean("Test.Example.Test"));
        assertTrue(nonExistent.exists());
    }
```
It is looks like 525 exception is caused by a exception that is not logged properly (Or I did not notice)

Here is the code that is used to create a new Config
```
    public Config(File file) {
        ...
        try {
            if (!file.exists()) {
// If this throws IOException absolutePath will be null, causing the issue later.
                file.createNewFile();
            }
            this.absolutePath = file.getAbsolutePath();

            read();
        } catch (IOException e) {
            Log.toLog(this.getClass().getName(), e);
        }
    }
```
I'll try swapping the order around and see if it fixes this issue.

I was unable to reproduce the issue with other means that use the plugin code (On a server or otherwise) but file stuff is pain to reproduce so I'll leave it.

**Comment by Rsl1122** [comment] 2018-03-31 11:53
Possibly fixed by https://github.com/Rsl1122/Abstract-Plugin-Framework/commit/7a93e78cc5cd5c59ac19e4cdbd53cb0db1ef0e40

**Closed** 2018-04-02 08:21 UTC
Labels: Bug, Complexity: HIGH, status: Possibly Fixed
