### ISSUE TITLE
Debug information and etcs

### ISSUE THREAD

**Issue by M1SM4TCH** [Rsl1122/Plan-PlayerAnalytics#535] opened 2018-02-23 23:47 UTC
**Description of the issue**

Doesn't show any information on panel
And a message on the console told me to create the issue
https://hastebin.com/ecivuwaxac.bash

----
Suggestions:

A hook with EpicSpawners and PermissionsEX/LuckPerms?
(If it's a duplicate suggestion, ignore it)

----
Can you send me a locale example? I would like to work on a Portuguese translation.

**Comment by Rsl1122** [comment] 2018-02-24 10:59
Could you describe the issue a bit more? Which information and what panel are you referring to? (`/server`-page? some other page?) - You have clearly been able to access the `/debug`-page, which is good.

----

You can obtain a copy of the English locale by setting `WriteLocaleOnEnable: true` and using `/plan reload`

**Comment by Rsl1122** [comment] 2018-02-24 11:08
The Bug in this is a duplicate of #525 & it's stack trace has been placed there.

**Comment by Rsl1122** [comment] 2018-02-24 11:10
Split suggestion to separate ticket

**Closed by Rsl1122** 2018-02-24 11:10 UTC
Labels: Bug, Multi-Issue, PluginData, Question, Suggestion, status: Done
