### ISSUE TITLE
500 Internal Error occurred

### ISSUE THREAD

**Issue by aztecwalker** [Rsl1122/Plan-PlayerAnalytics#441] opened 2017-12-02 18:06 UTC
I've done everything like the Set-Up page..
I'm no using Bungee
I've use version 4.0.7 Before and running on the server like a charm..
I've deleted the data before and install this new update 4.1.0 and end up with this error

java.lang.ArithmeticException: / by zero | Analysis
    main.java.com.djrapitops.plan.utilities.analysis.AnalysisUtils.calculateProbabilityOfStaying(AnalysisUtils.java:205)
    main.java.com.djrapitops.plan.data.AnalysisData.stuckPerDay(AnalysisData.java:253)
    main.java.com.djrapitops.plan.data.AnalysisData.stickiness(AnalysisData.java:239)
    main.java.com.djrapitops.plan.data.AnalysisData.onlineActivityNumbers(AnalysisData.java:210)
    main.java.com.djrapitops.plan.data.AnalysisData.analyze(AnalysisData.java:124)
    main.java.com.djrapitops.plan.utilities.analysis.Analysis.analyzeData(Analysis.java:131)
    main.java.com.djrapitops.plan.utilities.analysis.Analysis.analyze(Analysis.java:97)
    main.java.com.djrapitops.plan.utilities.analysis.Analysis$1.run(Analysis.java:70)
    com.djrapitops.plugin.task.RunnableFactory$1.run(RunnableFactory.java:38)
    org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
    org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
    java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    java.lang.Thread.run(Thread.java:745)

![111](https://user-images.githubusercontent.com/33455446/33518355-97426d4c-d7ce-11e7-8dd5-b8494590288e.PNG)

**Comment by Rsl1122** [comment] 2017-12-02 18:09
Duplicate of #438

**Closed** 2017-12-02 18:10 UTC
Labels: Duplicate, status: Done

**Comment by Rsl1122** [comment] 2017-12-02 18:12
Fix has been uploaded to spigot.

**Comment by aztecwalker** [comment] 2017-12-02 18:27
Thank you sir
