### ISSUE TITLE
List of suggestions

### ISSUE THREAD

**Issue by FrozenBeard** [Rsl1122/Plan-PlayerAnalytics#125] opened 2017-06-07 13:33 UTC
- [x] 1. Record TPS over time, so we can have a graph of TPS.
- [x] 2. Have an option to hide the plugins in the config, This way this data can be shared with staff without giving away all the plugins.
- [x] 3. Can you do some testing in FireFox please? Im having issues with pages not loading sometimes.
- [x] 4. Can we have a statistic for Most online players at a time/date. It would be nice to see the busiest time ever.
- [x] 5. plug-in compatibility; Could I see some data from GriefPrevention be displayed please, this is a massive plugin and would be great data to show.
- [ ] 6. plug-in compatibility; Luckperms, For a lot of us we have been running a lot longer than we have had plan installed, so we dont have a full user list, if you add compatibility with Luckperms, you can pull a whole server list, as well as everyones groups, this gives a whole new section to the plan, you can have a statistics page dedicated to Groups, how many people are in a certain group etc, how quickly people move from 1 group to another.
- [x] 7. plug-in compatibility; Just for showing (bans) we use banmanager, could easily pull, they have an API too.
- [x] 8. plug-in compatibility; ViaVersion, This allows newer clients to conect to an older server, you could show data for the Clients connecting, to see if most people are using say 1.12, of if people are still using 1.11.
- [ ] 9. plug-in expandability; Basic Economy statistics taken from Essentails Eco; You could hook into Essentails Eco and gather money spent/accumulated for players per day, this all goes through vault I think.
- [x] 10. plug-in compatibility; AAC, Biggest anti-cheat by far, you could display the most flagged people for cheating, people that are most likely to be using a hacked client, this could be a game changing statistic! The datas there, they have an API.

(Split by Rsl from 6.):
- [x] 11. Import server's offline playerbase that has not joined after Plan was installed

Quite a bit to chew on there, just in case you need some ideas.

**Comment by Rsl1122** [comment] 2017-06-08 09:40
One duplicate with #98

**Comment by Rsl1122** [comment] 2017-06-11 19:20
3. Will be testing in Firefox for 3.4.3.
9. Essentials Eco does use Vault, but vault doesn't provide an interface for saving transaction history. I will look at EssentialsEco. Most of the Plugin compatibility additions will arrive in 3.5.0

**Comment by Rsl1122** [comment] 2017-06-27 10:47
The page loading issue might be caused by minotar player icons.
Next version will include a config setting to disable them on analysis page.

**Comment by Rsl1122** [comment] 2017-07-26 08:46
If the page loading issue has not yet been fixed it will be fixed with the HTTPS server.

**Comment by FrozenBeard** [comment] 2017-07-26 15:47
You are really hammering through these suggestions! Awesome work!

**Comment by FrozenBeard** [comment] 2018-02-11 01:19
Hey @Rsl1122 If you haven't been told already, thank you so much for doing all these updates and adding all these new features to Plan, I haven't used plan since version 3.4 Up until this week, where I did a fresh install and was absolutely amazed to see the progress you have made, its like its been re-built from the ground up, im stunned at the work you have put in.
So a giant thank you from the whole team at PirateCraft, we will be using this as a magnificent tool, the additions for GriefPrevention, AAC and Banmanager are epic, we can see an overview for a player in one place, I will be reading up on how to edit the HTML myself to add in links to my banmanager webUI direct from that user page!

Great work, thanks a million, I really appreciate the hard work.

**Comment by Rsl1122** [comment] 2018-02-11 07:52
Thanks :)

Yes, I think it has been rebuilt by now :D
4.0.0 - Bungee support, required massive database changes
4.1.0 - Front end rewrite (Totally worth it to have moved to a bootstrap template) 
4.1.5 (Upcoming) - Massive refactoring, modularized the plugin to ease development & rewrote Bungee-Bukkit connections to be much simpler

You can join discord for more updates, support and discussions :)

**Comment by FrozenBeard** [comment] 2018-02-11 11:12
Oh awesome! I also noticed you are making/made an API? I think I got the wrong idea though, is it only for internal java plugins to query? I have a raspberry pi sat on my desk with an oldschool 20x4 lcd display attached that shows me my player count on, I was going to query plan to pull in playercount, top online etc, If not no biggie Ill pull it direct from the MySQL!

**Comment by Rsl1122** [comment] 2018-02-11 14:05
You can follow #506 for HTTP based API arriving :)

**Comment by Rsl1122** [comment] 2018-05-24 19:07
Closing the issue as the remaining suggestions have been added to a new multi issue

**Closed by Rsl1122** 2018-05-24 19:07 UTC
Labels: Multi-Issue, PluginData, Suggestion

**Comment by rafalohaki** [comment] 2025-01-15 01:07
viaversion timeframe, from what date to what date which version was used

**Comment by AuroraLS3** [comment] 2025-01-15 05:34
@rafalohaki Old tickets are not considered for further features, please open a new one with more details.
