### ISSUE TITLE
Missing details in accordionSessions

### ISSUE THREAD

**Issue by SlimeDog** [Rsl1122/Plan-PlayerAnalytics#690] opened 2018-08-20 07:11 UTC
Spigot 1.13 latest
Plan 4.4.3-b1 (aka 4.4.4 DEV1) heavily customized 

Most Recent Sessions ${accordionSessions} does not display session details in header, and does not display worldGraph. The database table entries look correct. An example:

![untitled](https://user-images.githubusercontent.com/17748923/44325207-f8785a80-a40c-11e8-8dc5-5b2c9a11119a.png)

There are no console/log errors, or relevant indications of anything amiss when _Debug:true_.

No doubt, I have misconfigured something, but I do not see it.

**Comment by Rsl1122** [comment] 2018-08-20 07:46
It would appear that this is related to the World Aliases - I managed to reproduce the `- (-)` for all sessions, but not the pie chart missing

I'll get back to you after investigating more.

**Comment by Rsl1122** [comment] 2018-08-20 07:58
This bug was caused by improper setter at 
https://github.com/Rsl1122/Plan-PlayerAnalytics/blob/master/Plan/src/main/java/com/djrapitops/plan/data/container/Session.java#L157

The longest world calculation did not use the DataContainer value, but instead used the stored WorldTimes class variable - Which was empty if fetched from database due to the wrong setter.

----

For the empty world pie, please check that your `server.html`
contains:

```
        ...
        horizontalBarChart('countryBarChart', v.data.countryCategories, [series.country], 'Players');
        lineChart('pingGraph', [series.avgPing, series.maxPing, series.minPing]);
        ${sessionTabGraphViewFunctions} // <-- Important line
```

**Comment by Rsl1122** [comment] 2018-08-20 08:49
Should be fixed in DEV2

Let me know if the blank pie issue persists and I'll reopen the issue.

**Closed by Rsl1122** 2018-08-20 08:49 UTC
Labels: Bug, status: Reproduced

**Comment by SlimeDog** [comment] 2018-08-20 11:49
Spigot 1.13 latest
Plan 4.4.3-b2 (aka 4.4.4-DEV2)

Session detail are now displayed in headers. Thanks.

WorldPie is not displayed in expanded sessions.
![untitled](https://user-images.githubusercontent.com/17748923/44338550-0c36b780-a433-11e8-953a-77110df6c1a8.png)

server.html contains (and did contain)
```
        horizontalBarChart('countryBarChart', v.data.countryCategories, [series.country], 'Players');
        lineChart('pingGraph', [series.avgPing, series.maxPing, series.minPing]);
        ${sessionTabGraphViewFunctions};
```
(Note semicolon, which I think is correct, but does not change the outcome in any event.)

**Comment by Rsl1122** [comment] 2018-08-20 12:31
Great that it is fixed now :)
