### ISSUE TITLE
Exception can be viewed

### ISSUE THREAD

**Issue by TheKillHDmc** [Rsl1122/Plan-PlayerAnalytics#537] opened 2018-02-24 13:51 UTC
Hello, this error is spamming my console :  https://pastebin.com/Ff1h9NKf

Error log : https://pastebin.com/pR485eVw

**Comment by Rsl1122** [comment] 2018-02-24 14:32
./plan reload  should keep it at bay for some time. Looks like a duplicate of #489

**Comment by TheKillHDmc** [comment] 2018-02-24 14:38
looks good, thanks !

**Closed** 2018-02-24 18:12 UTC
Labels: Bug, Duplicate
