### ISSUE TITLE
Exception in Minecraft Log when accessing web page

### ISSUE THREAD

**Issue by kaiarne** [Rsl1122/Plan-PlayerAnalytics#949] opened 2019-03-05 22:33 UTC
### Describe the bug
Exception in server.log on every web page access - web page contines reloading

### Server information
git-Spigot-3cb9dcb-0f708cb (MC: 1.13.2) 

Errors occurring with 4.7.0 and 4.7.1-dev; 
after reverting to 4.6.2 it works fine

### Exceptions & Other Logs
[06:02:36] [Plan Non critical-pool-2/WARN]: [Plan] Error was caught by com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest
com.djrapitops.plan.api.exceptions.connection.InternalErrorException: Analysis failed due to exception
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.analyseAndGetHtml(GenerateAnalysisPageRequest.java:130) ~[?:?]
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.generateAndCache(GenerateAnalysisPageRequest.java:113) ~[?:?]
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.lambda$null$1(GenerateAnalysisPageRequest.java:105) ~[?:?]
        at com.djrapitops.plan.system.info.connection.WebExceptionLogger.logIfOccurs(WebExceptionLogger.java:57) ~[?:?]
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.lambda$handleRequest$2(GenerateAnalysisPageRequest.java:105) ~[?:?]
        at com.djrapitops.plan.system.processing.Processing.lambda$submitNonCritical$0(Processing.java:73) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.IllegalStateException: Duplicate key JuSe1
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133) ~[?:1.8.0_202]
        at java.util.HashMap.merge(HashMap.java:1254) ~[?:1.8.0_202]
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320) ~[?:1.8.0_202]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_202]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_202]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_202]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_202]
        at com.djrapitops.plan.data.store.containers.AnalysisContainer.lambda$addPlayerSuppliers$8(AnalysisContainer.java:167) ~[?:?]
        at com.djrapitops.plan.data.store.CachingSupplier.get(CachingSupplier.java:50) ~[?:?]
        at com.djrapitops.plan.data.store.containers.SupplierDataContainer.getUnsafe(SupplierDataContainer.java:107) ~[?:?]
        at com.djrapitops.plan.data.store.containers.DynamicDataContainer.getUnsafe(DynamicDataContainer.java:80) ~[?:?]
        at com.djrapitops.plan.data.store.containers.AnalysisContainer.lambda$null$49(AnalysisContainer.java:308) ~[?:?]
        at com.djrapitops.plan.utilities.html.structure.SessionAccordion.addElementsForServer(SessionAccordion.java:109) ~[?:?]
        at com.djrapitops.plan.utilities.html.structure.SessionAccordion.addElements(SessionAccordion.java:102) ~[?:?]
        at com.djrapitops.plan.utilities.html.structure.SessionAccordion.<init>(SessionAccordion.java:91) ~[?:?]
        at com.djrapitops.plan.utilities.html.structure.Accordions.serverSessionAccordion(Accordions.java:107) ~[?:?]
        at com.djrapitops.plan.data.store.containers.AnalysisContainer.lambda$addSessionSuppliers$50(AnalysisContainer.java:302) ~[?:?]
        at com.djrapitops.plan.data.store.CachingSupplier.get(CachingSupplier.java:50) ~[?:?]
        at com.djrapitops.plan.data.store.containers.SupplierDataContainer.getUnsafe(SupplierDataContainer.java:107) ~[?:?]
        at com.djrapitops.plan.data.store.containers.DynamicDataContainer.getUnsafe(DynamicDataContainer.java:80) ~[?:?]
        at com.djrapitops.plan.data.store.containers.AnalysisContainer.lambda$addSessionSuppliers$51(AnalysisContainer.java:310) ~[?:?]
        at com.djrapitops.plan.data.store.containers.SupplierDataContainer.getValue(SupplierDataContainer.java:95) ~[?:?]
        at com.djrapitops.plan.data.store.containers.DynamicDataContainer.getValue(DynamicDataContainer.java:71) ~[?:?]
        at com.djrapitops.plan.utilities.formatting.PlaceholderReplacer.addPlaceholderFrom(PlaceholderReplacer.java:35) ~[?:?]
        at com.djrapitops.plan.utilities.formatting.PlaceholderReplacer.addAllPlaceholdersFrom(PlaceholderReplacer.java:40) ~[?:?]
        at com.djrapitops.plan.utilities.html.pages.AnalysisPage.sessionStructures(AnalysisPage.java:116) ~[?:?]
        at com.djrapitops.plan.utilities.html.pages.AnalysisPage.toHtml(AnalysisPage.java:89) ~[?:?]
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.analyseAndGetHtml(GenerateAnalysisPageRequest.java:128) ~[?:?]
        ... 9 more

**Comment by Rsl1122** [comment] 2019-03-06 05:40
Duplicate of #942

Fix will be released today.

**Closed by Rsl1122** 2019-03-06 05:40 UTC

**Comment by kaiarne** [comment] 2019-03-06 15:12
For us It's not fixed with today's release of 4.7.1

[16:11:23 WARN]: [Plan] Error was caught by com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest
com.djrapitops.plan.api.exceptions.connection.InternalErrorException: Analysis failed due to exception
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.analyseAndGetHtml(GenerateAnalysisPageRequest.java:130) ~[?:?]
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.generateAndCache(GenerateAnalysisPageRequest.java:113) ~[?:?]
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.lambda$null$1(GenerateAnalysisPageRequest.java:105) ~[?:?]
        at com.djrapitops.plan.system.info.connection.WebExceptionLogger.logIfOccurs(WebExceptionLogger.java:57) ~[?:?]
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.lambda$handleRequest$2(GenerateAnalysisPageRequest.java:105) ~[?:?]
        at com.djrapitops.plan.system.processing.Processing.lambda$submitNonCritical$0(Processing.java:73) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_202]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_202]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.IllegalStateException: Duplicate key JuSe1
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133) ~[?:1.8.0_202]
        at java.util.HashMap.merge(HashMap.java:1254) ~[?:1.8.0_202]
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320) ~[?:1.8.0_202]
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:1.8.0_202]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_202]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_202]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_202]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_202]
        at com.djrapitops.plan.data.store.containers.AnalysisContainer.lambda$addPlayerSuppliers$8(AnalysisContainer.java:167) ~[?:?]
        at com.djrapitops.plan.data.store.CachingSupplier.get(CachingSupplier.java:50) ~[?:?]
        at com.djrapitops.plan.data.store.containers.SupplierDataContainer.getUnsafe(SupplierDataContainer.java:107) ~[?:?]
        at com.djrapitops.plan.data.store.containers.DynamicDataContainer.getUnsafe(DynamicDataContainer.java:80) ~[?:?]
        at com.djrapitops.plan.data.store.containers.AnalysisContainer.lambda$null$49(AnalysisContainer.java:308) ~[?:?]
        at com.djrapitops.plan.utilities.html.structure.SessionAccordion.addElementsForServer(SessionAccordion.java:109) ~[?:?]
        at com.djrapitops.plan.utilities.html.structure.SessionAccordion.addElements(SessionAccordion.java:102) ~[?:?]
        at com.djrapitops.plan.utilities.html.structure.SessionAccordion.<init>(SessionAccordion.java:91) ~[?:?]
        at com.djrapitops.plan.utilities.html.structure.Accordions.serverSessionAccordion(Accordions.java:107) ~[?:?]
        at com.djrapitops.plan.data.store.containers.AnalysisContainer.lambda$addSessionSuppliers$50(AnalysisContainer.java:302) ~[?:?]
        at com.djrapitops.plan.data.store.CachingSupplier.get(CachingSupplier.java:50) ~[?:?]
        at com.djrapitops.plan.data.store.containers.SupplierDataContainer.getUnsafe(SupplierDataContainer.java:107) ~[?:?]
        at com.djrapitops.plan.data.store.containers.DynamicDataContainer.getUnsafe(DynamicDataContainer.java:80) ~[?:?]
        at com.djrapitops.plan.data.store.containers.AnalysisContainer.lambda$addSessionSuppliers$51(AnalysisContainer.java:310) ~[?:?]
        at com.djrapitops.plan.data.store.containers.SupplierDataContainer.getValue(SupplierDataContainer.java:95) ~[?:?]
        at com.djrapitops.plan.data.store.containers.DynamicDataContainer.getValue(DynamicDataContainer.java:71) ~[?:?]
        at com.djrapitops.plan.utilities.formatting.PlaceholderReplacer.addPlaceholderFrom(PlaceholderReplacer.java:35) ~[?:?]
        at com.djrapitops.plan.utilities.formatting.PlaceholderReplacer.addAllPlaceholdersFrom(PlaceholderReplacer.java:40) ~[?:?]
        at com.djrapitops.plan.utilities.html.pages.AnalysisPage.sessionStructures(AnalysisPage.java:116) ~[?:?]
        at com.djrapitops.plan.utilities.html.pages.AnalysisPage.toHtml(AnalysisPage.java:89) ~[?:?]
        at com.djrapitops.plan.system.info.request.GenerateAnalysisPageRequest.analyseAndGetHtml(GenerateAnalysisPageRequest.java:128) ~[?:?]
        ... 9 more

**Comment by Rsl1122** [comment] 2019-03-06 15:16
Looks like I misread the error. It is not a duplicate of the issue I marked it a duplicate of in the morning. (That issue was about WorldMap, this one is about SessionAccordion)

Follow issue #956 for resolution to this error.
